### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ChuckMate** [defray-labs/sovryn-mobile#143]
**Describe the bug**

App constantly closes when trying to send eSOV. 

**To Reproduce**
1. Go to “send”
2. Click on “wallet address and paste”
3. Scroll down to “network and switch to eSOV”
4. See error “app instantly closes”

**Expected behavior**
App is suppose to process sending

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: 17

**Additional context**

**Comment by grinry** [comment]
issue fixed, updated app should be released early next week.
