### ISSUE TITLE
Bug on Passcode & Fingerprints

### ISSUE THREAD

**Issue by bitcoinuser** [defray-labs/sovryn-mobile#51]
![photo_2022-02-11_10-20-45](https://user-images.githubusercontent.com/1178856/153599415-5e48ad7e-300f-4c96-8fe0-a2ff02f51f69.jpg)

**Comment by harmaus** [comment]
It's when trying to confirm transaction or in settings perhaps?

**Comment by harmaus** [comment]
Hey @bitcoinuser, which device you used?

**Comment by bitcoinuser** [comment]
This is fixed. Thanks
