### ISSUE TITLE
I needed to click two times on asset button after I hide the keyboard to open the list of assets

### ISSUE THREAD

**Issue by bitcoinuser** [defray-labs/sovryn-mobile#68]
Hi,

I needed to click two times on asset button after I hide the keyboard to open the list of assets. Should be one click to open the list of assets.

![photo_2022-02-14_18-35-41](https://user-images.githubusercontent.com/1178856/153950394-6df3db6e-02a7-41b5-aea5-0b817bbb83d6.jpg)

**Comment by bitcoinuser** [comment]
Maybe even with keyboard opened, if we click on assets, could open the list, instead of hide keyboard too. Is it possible?

**Comment by harmaus** [comment]
Steps to reproduce would be like this?:
- open keyboard
- close keyboard
- click on asset / balance (nothing happens)
- click on asset / balance (works now)

It should indeed work right away without clicking twice
