### ISSUE TITLE
Even with android back and with close button, I think when clicking outside the window, should close too

### ISSUE THREAD

**Issue by bitcoinuser** [defray-labs/sovryn-mobile#69]
Hi,

Even with android back and with close button, I think when clicking outside the window, should close too

![photo_2022-02-14_18-35-48](https://user-images.githubusercontent.com/1178856/153950678-d482da4d-2a40-4085-b9d0-a3d267728d67.jpg)

**Comment by harmaus** [comment]
Hey, this modal also closes by dragging it out of the screen (to the bottom), I'm planning on adding visible handle later so it would be clear it does so.
But will make some research if it's ok to have close on click-outside.
